name: obesity_management_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0  # 상태 관리를 위해
  http: ^1.2.1     # API 호출을 위해
  shared_preferences: ^2.0.0  # 로컬 저장소를 위해
  uuid: ^4.4.0
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  